language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
  - functions/node_modules
install:
- npm install -g npm@latest
- npm ci
- (cd functions && npm ci)
script:
- npm run dist
after_script:
- ./travis-deploy.sh
