image: node:9.8

pipelines:
  branches:
    master:
    - step:
        caches:
        - node
        script:
        - npm ci
        - npm run dist
        - npx firebase deploy --token $FIREBASE_TOKEN
