image: node:9.8

pipelines:
  branches:
    master:
    - step:
        name: Install dependencies
        caches:
        - node
        script:
        - npm install -g npm@latest
        - npm ci
        - (cd functions && npm ci)
    - step:
        name: Build
        caches:
        - node
        script:
        - npm run dist
    - step:
        name: Deploy
        caches:
        - node
        script:
        - npm run deploy -- --token $FIREBASE_TOKEN
        deployment: production
