image: node:9.8

pipelines:
  branches:
    master:
    - step:
        caches:
        - node
        script:
        - npm install -g npm@latest
        - npm ci
        - (cd functions && npm ci)
        - npm run dist
        - npm run deploy:functions -- --token $FIREBASE_TOKEN
        - npm run deploy:hosting -- --token $FIREBASE_TOKEN
