image: node:8.6.0

pipelines:
  branches:
    master:
    - step:
        name: Install yarn
        script:
        - curl -o- -fsSL https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
        - export PATH=$HOME/.yarn/bin:$PATH
    - step:
        name: Install dependencies
        caches:
        - node
        script:
        - yarn install --frozen-lockfile --non-interactive
    - step:
        name: Build
        caches:
        - node
        script:
        - npm run dist
    - step:
        name: Deploy
        caches:
        - node
        script:
        - node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN
