image: node:9.8

pipelines:
  branches:
    master:
    - step:
        caches:
        - node
        script:
        - npm install -g npm@latest
        - npm ci
        - (cd functions && npm ci)
        - npm run dist
        - npm run deploy -- --token $FIREBASE_TOKEN
        deployment: production
