image: node:8.6.0

pipelines:
  branches:
    master:
    - step:
        caches:
        - node
        script:
        - curl -o- -fsSL https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
        - export PATH=$HOME/.yarn/bin:$PATH
        - yarn install --frozen-lockfile --non-interactive
        - npm run dist
        - 'echo "Firebase token: $FIREBASE_TOKEN"'
        - node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
