const config = {
  baseUrl: "https://ferienspiele-rothenbergen.de",
  apiUrl: "https://europe-west3-ferienspiele-rothenbergen-2.cloudfunctions.net",
  app: "Ökumenische Ferienspiele für Niedergründau und Rothenbergen",
  title: "Zeitreise",
  year: 2024,
  startDate: new Date("2024-07-15"),
  endDate: new Date("2024-07-19"),
  registrationStart: new Date("2024-05-01T06:00:00Z"),
  registrationDeadline: new Date("2024-05-31"),
  waiverDeadline: new Date("2024-06-14"),
  maxParticipants: 66,
  earlyCarePlaces: 15,
  prices: {
    base: 45,
    sibling: -15,
    noCake: 10,
  },
  kuchen: [
    { date: "2024-07-15", amount: 10 },
    { date: "2024-07-16", amount: 10 },
    { date: "2024-07-17", amount: 10 },
    { date: "2024-07-18", amount: 10 },
  ],
  genders: [
    { value: "m", label: "männlich" },
    { value: "f", label: "weiblich" },
    { value: "d", label: "divers" },
  ],
  shirtSizes: [
    { value: "WOMEN_XS", label: "Damen XS" },
    { value: "WOMEN_S", label: "Damen S" },
    { value: "WOMEN_M", label: "Damen M" },
    { value: "WOMEN_L", label: "Damen L" },
    { value: "WOMEN_XL", label: "Damen XL" },
    { value: "WOMEN_XXL", label: "Damen XXL" },
    { value: "MEN_XS", label: "Herren XS" },
    { value: "MEN_S", label: "Herren S" },
    { value: "MEN_M", label: "Herren M" },
    { value: "MEN_L", label: "Herren L" },
    { value: "MEN_XL", label: "Herren XL" },
    { value: "MEN_XXL", label: "Herren XXL" },
    { value: "MEN_XXXL", label: "Herren XXXL falls verfügbar, sonst XXL" },
    { value: "CHILDREN_S", label: "Kinder 7-8 Jahre (122/128)" },
    { value: "CHILDREN_M", label: "Kinder 9-11 Jahre (134/146)" },
    { value: "CHILDREN_L", label: "Kinder 12-14 Jahre (152/164)" },
  ],
  foodPreferences: [
    { value: "omnivore", label: "Mein Kind isst Fleisch" },
    { value: "vegetarian", label: "Mein Kind isst vegetarisch" },
    { value: "vegan", label: "Mein Kind isst vegan" },
  ],
};

export default config;
