name: deploy functions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: Production
    runs-on: ubuntu-latest
    concurrency: functions

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: '14.19.1'
          cache: npm
          cache-dependency-path: |
            package-lock.json
            functions/package-lock.json

      - name: npm
        run: npm i -g npm@8.8.0

      - name: install
        run: npm ci

      - name: install functions
        run: npm ci
        working-directory: functions

      - name: build
        run: npm run build-functions
        working-directory: functions

      - name: deploy
        run: npm run deploy:functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
