name: deploy functions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: Production
    runs-on: ubuntu-latest
    concurrency: functions

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache-dependency-path: |
            package-lock.json
            functions/package-lock.json

      - name: Cache dependencies
        id: npm-cache-functions
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json', 'functions/package-lock.json') }}

      - name: Install
        if: steps.npm-cache-functions.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Install functions
        if: steps.npm-cache-functions.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
        working-directory: functions

      - name: Build
        run: npm run build-functions
        working-directory: functions

      - name: Deploy
        run: npm run deploy:functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
