name: deploy gui

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: Production
    runs-on: ubuntu-22.04
    concurrency: gui

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          node-version-file: package.json

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"

      - name: Deploy
        run: pnpm deploy:hosting
