name: deploy functions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: Production
    runs-on: ubuntu-22.04
    concurrency: functions

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: functions/package.json

      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            functions/node_modules
          key: npm-${{ hashFiles('package-lock.json', 'functions/package-lock.json') }}

      - name: Install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci && (cd functions && npm ci)

      - name: Build
        run: npm run build-functions
        working-directory: functions

      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"

      - name: Configure environment
        run: |
          echo "GMAIL_EMAIL=${{ vars.GMAIL_EMAIL }}" >> functions/.env
          echo "GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}" >> functions/.env

      - name: Deploy
        run: npm run deploy:functions
